# Generated by Django 6.0 on 2026-01-06 12:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_enquiry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
